apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-ui
  labels:
    app: karsajobs-ui
    tier: karsajobs-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: karsajobs-ui
  template:
    metadata:
      labels:
        app: karsajobs-ui
        tier: karsajobs-ui
    spec:
      containers:
      - name: karsajobs-ui
        image: aluth313/karsajobs-ui:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8000
        env:
          - name: VUE_APP_BACKEND
            value: http://127.0.0.1:46579