apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs
  labels:
    app: karsajobs
    tier: karsajobs
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: karsajobs
  template:
    metadata:
      labels:
        app: karsajobs
        tier: karsajobs
    spec:
      containers:
      - name: karsajobs
        image: aluth313/karsajobs:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        env:
          - name: APP_PORT
            value: "8080"
          - name: MONGO_HOST
            value: "http://mongo.submission2-ns:27017"
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: MONGO_ROOT_USERNAME
          - name: MONGO_PASS
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: MONGO_ROOT_PASSWORD